# -*- coding: utf-8 -*-
"""【AI Agents】打造專屬的超級代理人_年度公關災難的危機處理思考生成器Two_Stage_CoT版(東華大學 611421501 資工碩專一 曾建瑋).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EW-4IqMs5o4g_AEgAZV-L5uQVDn_cANm

### 🎯 CoT 題目：年度公關災難的危機處理
原始任務：這個角色負責像顧問一樣，客觀地分解危機的成因和影響。

### 應用目標
- 輸入： 一個企業的公關危機事件概要（例如：某醫學中心的資安問題、某連鎖餐廳的衛生問題、某科技公司的高層失言）。
- 輸出： 危機的專業診斷（Planner）和三階段的危機處理策略（Writer）。


#### ✅ CoT 改寫版本流程：
1. **第一階段（診斷階段 - Planner CoT）**：
- 請 LLM 針對使用者輸入的企業公關危機事件，識別其核心問題類型（例如：產品缺陷、流程疏失）。
- 從風險管理標準出發，思考並列出四個嚴謹的關鍵診斷點，支持「該危機的嚴重性與系統性衝擊」的觀點。

2. **第二階段（策略階段 - Writer CoT）**：
* 核心問題聚焦： 從上述四個診斷點中，選出一個最需要立即處理的核心問題。
* 三階段策略設計： 根據該核心問題，請 LLM 以專業品牌策略師的風格，設計一套包含以下三期的危機應對策略：
    - 止血期（24小時內）： 明確的應對目標與對公眾的溝通內容。
    - 修復期（短期承諾）： 具體補救措施與恢復消費者信任的行動承諾。
    - 重建期（長期願景）： 將危機轉化為品牌長期改進的計畫。

總結： 這就是典型的 「拆解爭議 → 嚴謹分析 → 整合論證 → 輸出結論」 的 CoT 應用模式。

#### 1. 讀入你的金鑰

請依你使用的服務, 決定讀入哪個金鑰
"""

import os
from google.colab import userdata

#【使用 Mistral】
# api_key = userdata.get('Mistral')
# os.environ['MISTRAL']=api_key
# provider = "mistral"
# model = "ministral-8b-latest"

#【使用 OpenAI】
# api_key = userdata.get('OpenAI')
# os.environ['OPENAI_API_KEY']=api_key
# provider = "openai"
# model = "gpt-4o"

#【使用 Groq】
api_key = userdata.get('Groq')
os.environ['GROQ_API_KEY']=api_key
provider = "groq"
model = "openai/gpt-oss-120b"

!pip install aisuite[all]

"""### 2. 使用 AISuite 的準備"""

import aisuite as ai

provider_planner = "groq"
model_planner="openai/gpt-oss-120b"

provider_writer = "groq"
model_writer = "openai/gpt-oss-120b"

# provider_planner = "groq"
# model_planner = "llama-3.3-70b-versatile"

# provider_writer = "groq"
# model_writer = "llama-3.3-70b-versatile"

#provider_reviewer = "openai"
#model_reviewer = "gpt-4o"

def reply(system="請用台灣習慣的中文回覆。",
          prompt="Hi",
          provider="groq",
          model="openai/gpt-oss-120b"
          ):

    client = ai.Client()

    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": prompt}
    ]


    response = client.chat.completions.create(model=f"{provider}:{model}", messages=messages)

    return response.choices[0].message.content

"""####  3. 打造二階段"""

system_planner = "請用台灣習慣的中文回應: 你是一位頂尖的品牌危機管理顧問，專精於公關與風險分析。你的任務是執行 CoT 推理：針對使用者輸入的企業危機事件，依序思考並列出四個『診斷危機』的關鍵論證點。論證點需涵蓋危機成因、利害關係人衝擊、和公眾情緒三個維度。請以條列式清單呈現，每個論證點需包含一個『診斷方向』與『佐證的公關學或風險管理事實』。"
system_writer = "請用台灣習慣的中文回應: 你是一位專業且果斷的品牌策略師與公關執行長，擅長將嚴謹的危機分析結論，轉化為具體可行的三階段應對策略。請根據 Planner 提供的四個診斷點，設計一個『既誠懇又有效』的危機處理策略。策略必須涵蓋：1. 止血期（24h內）、2. 修復期（短期承諾）、3. 重建期（長期願景）。結尾請用一句話總結該企業度過危機的成功關鍵，並加入一個能展現專業態度的emoji。"

def lucky_post(prompt):
    # Step 1: CoT - 這個 Prompt 強制模型將使用者輸入的事件作為分析對象，並進行嚴謹的分類診斷
    planning_prompt = (
        f"請根據使用者提供的公關危機事件：『{prompt}』，"
        f"執行你的 CoT 危機診斷步驟：\n"
        f"1. **危機類型識別**：簡要說明此事件屬於哪種危機類型（例如：產品缺陷、領導失言、流程疏失）。\n"
        f"2. **關鍵診斷**：請想出四個嚴謹的關鍵診斷點，用來支持『該企業當前情勢的嚴重性』。這四點必須分析其對『消費者』、『內部員工』、『投資者』和『品牌聲譽』的衝擊。\n"
        f"請直接輸出這四個診斷點的條列式清單。"
    )
    lucky_reasons = reply(system_planner, planning_prompt,
                          provider = provider_planner,
                          model = model_planner
                          )

    # Step 2: 這個 Prompt 強制模型以三段式的公關策略框架來組織輸出
    generation_prompt = (
        f"這是 Planner 提供的四個關鍵危機診斷點（即：\n{lucky_reasons}\n）。\n\n"
        f"請扮演品牌策略師，執行以下 CoT 策略制定流程：\n"
        f"1. **核心問題聚焦**：從上述診斷點中，選出一個『最需要立即處理』的核心問題。\n"
        f"2. **策略設計**：請根據該核心問題，為企業設計一個『既誠懇又有效』的三階段危機應對策略。請明確標示並說明以下三期目標：\n"
        f"   - **止血期（24小時內）**：行動目標與溝通內容。\n"
        f"   - **修復期（短期承諾）**：具體補救措施與恢復消費者信任的承諾。\n"
        f"   - **重建期（長期願景）**：如何將危機轉化為品牌長期改進的機會。\n"
        f"3. **總結**：以一句話總結該策略成功的關鍵，並輸出最終的策略報告。"
    )
    final_post = reply(system_writer, generation_prompt,
                       provider = provider_writer,
                       model = model_writer
                       )

    return lucky_reasons, final_post

"""### 4. 用 Gradio 打造你的對話機器人 Web App!"""

!pip install gradio

import gradio as gr

import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("### 🚨 品牌危機管理儀表板 Chain-of-Thought 推理 🛡️")
    # Add an image here. Replace 'your_image_path.jpg' with the actual path to your image file.
    # You can upload an image file to your Colab environment and use its path.
    gr.Image(value='https://uit.no/Content/791813/cache=20221410130805/transformation=scale10000x1500/21725999-crisis-word-cloud.jpg',width="400px", label="危機事件圖片")
    gr.Markdown("請輸入一個企業公關危機的事件概要（例如：某連鎖餐廳的衛生問題），讓 AI 扮演品牌顧問進行 CoT 診斷與策略制定。")
    user_input = gr.Textbox(label="請輸入欲分析的公關危機事件概要：", lines=3)
    btn = gr.Button("啟動 CoT 分析與評論 🚀")

    with gr.Row():
        out1 = gr.Textbox(label="📉 危機診斷與利害關係人衝擊分析 (Planner CoT)", lines=8)
        out2 = gr.Textbox(label="✅ 三階段危機應對策略 (Writer 執行報告)", lines=8)

    btn.click(lucky_post, inputs=[user_input], outputs=[out1, out2])

demo.launch(share=True, debug=True)